version: 2
jobs:
  deploy:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: 
          name: Deploy Master Branch
          command: |
            apk add --no-cache curl
            echo "Deploying project ..."
            find ./src/* -type f -exec curl -u "${FTP_USER}":"${FTP_PW}" --ftp-create-dirs -T {} ftp://"${FTP_HOST}"/website/{} \;

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
